FROM node:20-bullseye

WORKDIR /app

COPY package*.json ./
COPY scripts ./scripts
RUN npm ci && npm install cookie-parser jsonwebtoken bcrypt

COPY src ./src
COPY tsconfig.json ./tsconfig.json

ENV NODE_ENV=production
EXPOSE 3000

CMD ["npx", "tsx", "src/index.ts"]

